apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./

patches:
  - target:
      kind: Deployment
      group: apps
      version: v1
      name: rbacsync
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: this_value_is_ignored
      spec:
        template:
          spec:
            containers:
            - name: hello-world
              resources:
                requests:
                  memory: 100Mi
